[phases.setup]
nixPkgs = ["nodejs-18_x", "postgresql"]

[phases.install]
cmds = ["npm ci", "cd client && npm ci && cd .."]

[phases.build]
cmds = [
  "npx prisma generate",
  "cd client && npm run build && cd ..",
  "cp -r client/build ./public"
]

[start]
cmd = "npm start"

[variables]
NODE_ENV = "production"