[phases.setup]
nixPkgs = ["nodejs-18_x", "postgresql"]

[phases.install]
cmds = [
  "npm install --production=false",
  "cd client && npm install --production=false && cd .."
]

[phases.build]
cmds = [
  "npx prisma generate",
  "cd client && npm run build && cd ..",
  "rm -rf public",
  "cp -r client/build ./public"
]

[start]
cmd = "npx prisma migrate deploy && npm start"

[variables]
NODE_ENV = "production"